### ISSUE TITLE
arranging issue when a directory name have a no alphabet

### ISSUE THREAD

**Issue by computerphilosopher** [lukasgeiter/mkdocs-awesome-pages-plugin#10]
I classify documents by version number.

but build is failed when arrange entry have only numbers, 

# failed case

```
arrange:
    - 1.11-(latest)
    - 1.12
TypeError: Expected "arrange" attribute to be a list of strings - got <class 'list'> 
```

# success case

```
arrange:
    - 1.11-(latest)
    - 1.12-(develop)
```

**Comment by lukasgeiter** [comment]
YAML treats valid numbers as number therefore `1.12` is parsed as a number. To force a string, write it in quotes (single or double quotes):

```yaml
arrange:
    - 1.11-(latest)
    - "1.12"
```

**Comment by computerphilosopher** [comment]
it works. thank you for answering.
