### ISSUE TITLE
mkdocs 1.6.0 compatibility

### ISSUE THREAD

**Issue by phaer** [lukasgeiter/mkdocs-awesome-pages-plugin#103]
Hello & thanks for this great plugin, I added it to nixpkgs about a month ago.

Recently we've encountered test failures when using the newest mkdocs release, see the log below, and i found the following snippet in the changelog that might be relevant:

> The order of File objects inside a Files collection is no longer significant when automatically inferring the nav. They get forcibly sorted according to the default alphabetic order.

<details>

<summary>pytest log</summary>

<pre><code>_____________________________________________________ TestMkdocsNavRest.test_duplicate_item _____________________________________________________

self = <mkdocs_awesome_pages_plugin.tests.e2e.test_mkdocs_nav.TestMkdocsNavRest testMethod=test_duplicate_item>

    def test_duplicate_item(self):
        navigation = self.mkdocs(
            self.createConfig(mkdocs_nav=[{"2a": "2.md"}, {"2b": "2.md"}, "1.md", "..."]),
            ["1.md", "2.md", "3.md"],
        )

>       self.assertEqual(navigation, [("2a", "/2"), ("2b", "/2"), ("1", "/1"), ("3", "/3")])
E       AssertionError: Lists differ: [('2', '/2'), ('2', '/2'), ('1', '/1'), ('3', '/3')] != [('2a', '/2'), ('2b', '/2'), ('1', '/1'), ('3', '/3
E
E       First differing element 0:
E       ('2', '/2')
E       ('2a', '/2')
E
E       - [('2', '/2'), ('2', '/2'), ('1', '/1'), ('3', '/3')]
E       + [('2a', '/2'), ('2b', '/2'), ('1', '/1'), ('3', '/3')]
E       ?     +             +

mkdocs_awesome_pages_plugin/tests/e2e/test_mkdocs_nav.py:116: AssertionError
_________________________________________________________ TestMkdocsNavRest.test_titles _________________________________________________________

self = <mkdocs_awesome_pages_plugin.tests.e2e.test_mkdocs_nav.TestMkdocsNavRest testMethod=test_titles>

    def test_titles(self):
        navigation = self.mkdocs(
            self.createConfig(mkdocs_nav=[{"Title 2": "2.md"}, {"Title 1": "1.md"}, "..."]),
            ["1.md", "2.md", "3.md"],
        )

>       self.assertEqual(navigation, [("Title 2", "/2"), ("Title 1", "/1"), ("3", "/3")])
E       AssertionError: Lists differ: [('2', '/2'), ('1', '/1'), ('3', '/3')] != [('Title 2', '/2'), ('Title 1', '/1'), ('3', '/3')]
E
E       First differing element 0:
E       ('2', '/2')
E       ('Title 2', '/2')
E
E       - [('2', '/2'), ('1', '/1'), ('3', '/3')]
E       + [('Title 2', '/2'), ('Title 1', '/1'), ('3', '/3')]
E       ?    ++++++             ++++++

mkdocs_awesome_pages_plugin/tests/e2e/test_mkdocs_nav.py:131: AssertionError
__________________________________________________________ TestNav.test_duplicate_file __________________________________________________________

self = <mkdocs_awesome_pages_plugin.tests.e2e.test_nav.TestNav testMethod=test_duplicate_file>

    def test_duplicate_file(self):
        navigation = self.mkdocs(
            self.createConfig(mkdocs_nav=[{"1a": "1.md"}, {"2": "2.md"}, {"1b": "1.md"}]),
            ["1.md", "2.md", self.pagesFile(nav=["2.md", "1.md"])],
        )

>       self.assertEqual(navigation, [("2", "/2"), ("1b", "/1")])
E       AssertionError: Lists differ: [('2', '/2'), ('1a', '/1')] != [('2', '/2'), ('1b', '/1')]
E
E       First differing element 1:
E       ('1a', '/1')
E       ('1b', '/1')
E
E       - [('2', '/2'), ('1a', '/1')]
E       ?                  ^
E
E       + [('2', '/2'), ('1b', '/1')]
E       ?                  ^

mkdocs_awesome_pages_plugin/tests/e2e/test_nav.py:353: AssertionError
_______________________________________________________ TestNav.test_duplicate_file_rest ________________________________________________________

self = <mkdocs_awesome_pages_plugin.tests.e2e.test_nav.TestNav testMethod=test_duplicate_file_rest>

    def test_duplicate_file_rest(self):
        navigation = self.mkdocs(
            self.createConfig(mkdocs_nav=[{"1a": "1.md"}, {"2": "2.md"}, {"1b": "1.md"}]),
            ["1.md", "2.md", self.pagesFile(nav=["2.md", "..."])],
        )

>       self.assertEqual(navigation, [("2", "/2"), ("1a", "/1"), ("1b", "/1")])
E       AssertionError: Lists differ: [('2', '/2'), ('1a', '/1'), ('1a', '/1')] != [('2', '/2'), ('1a', '/1'), ('1b', '/1')]
E
E       First differing element 2:
E       ('1a', '/1')
E       ('1b', '/1')
E
E       - [('2', '/2'), ('1a', '/1'), ('1a', '/1')]
E       ?                                ^
E
E       + [('2', '/2'), ('1a', '/1'), ('1b', '/1')]
E       ?                                ^

mkdocs_awesome_pages_plugin/tests/e2e/test_nav.py:361: AssertionError
============================================================ short test summary info ============================================================
FAILED mkdocs_awesome_pages_plugin/tests/e2e/test_mkdocs_nav.py::TestMkdocsNavRest::test_duplicate_item - AssertionError: Lists differ: [('2', '/2'), ('2', '/2'), ('1', '/1'), ('3', '/3')] != [('2a', '/2'), ('2b', '/2'), ('1', '/1'), ('3', '/3')]
FAILED mkdocs_awesome_pages_plugin/tests/e2e/test_mkdocs_nav.py::TestMkdocsNavRest::test_titles - AssertionError: Lists differ: [('2', '/2'), ('1', '/1'), ('3', '/3')] != [('Title 2', '/2'), ('Title 1', '/1'), ('3', '/3')]
FAILED mkdocs_awesome_pages_plugin/tests/e2e/test_nav.py::TestNav::test_duplicate_file - AssertionError: Lists differ: [('2', '/2'), ('1a', '/1')] != [('2', '/2'), ('1b', '/1')]
FAILED mkdocs_awesome_pages_plugin/tests/e2e/test_nav.py::TestNav::test_duplicate_file_rest - AssertionError: Lists differ: [('2', '/2'), ('1a', '/1'), ('1a', '/1')] != [('2', '/2'), ('1a', '/1'), ('1b', '/1')]
=================================================== 4 failed, 280 passed, 1 skipped in 8.09s ====================================================

</code></pre>

</details>

**Comment by lukasgeiter** [comment]
Thanks for letting me know. I'll look into it 👍

**Comment by lukasgeiter** [comment]
I've released version 2.9.3 that should address these compatibility issues with MkDocs 1.6.0
