### ISSUE TITLE
Dividers

### ISSUE THREAD

**Issue by NFanoe** [lukasgeiter/mkdocs-awesome-pages-plugin#109]
Is it possible to add a divider or a piece of text with no link in the menu? To divide the menu items?

**Comment by lukasgeiter** [comment]
Not really. Since MkDocs doesn't support such a feature, that's not something this plugin can add.
If you're using the material theme though, you might be interested in this feature: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections

**Comment by NFanoe** [comment]
Thanks!

**Comment by NFanoe** [comment]
Thanks for the link.
