### ISSUE TITLE
Build fails if arrange-entry isn't existing

### ISSUE THREAD

**Issue by senacoralma** [lukasgeiter/mkdocs-awesome-pages-plugin#11]
Hey, your Plugin is awesome!

Unfortunately I encountered a small "missing feature" or for me a "bug". So if one of my entries in the arrange-list doesn't exists in the directory, the whole build of the MkDocs is failing.

Could you maybe add a option "strict" or something that is set to "True" in default (for not changing the current logic). If it's set to "False", even if the entry could not be found, there will be just printed a warning instead of raising an exception?

Thanks in advance!

**Comment by lukasgeiter** [comment]
Sounds like a good idea. I'll consider it for the next release.

**Comment by lukasgeiter** [comment]
The `strict` option is included in the latest version 2.2.0
