### ISSUE TITLE
UTF-8 encoding error

### ISSUE THREAD

**Issue by HP-ERNI-Victor** [lukasgeiter/mkdocs-awesome-pages-plugin#2]
Hi!
this plugin is awesome 👍 

but there is an error with files that are encoded with UTF-8, I had to edit the following line
`
 File "c:\users\perezv\appdata\local\programs\python\python36\lib\site-packages\mkdocs_awesome_pages_plugin\factory.py", line 68, in _create_leaf_page

with open(path, encoding='UTF-8') as file:
`
in order to get it to work on my project.

Thanks!

**Comment by lukasgeiter** [comment]
Hi! I'm glad you like the plugin and appreciate the bug report.
I've fixed the issue and released version 1.1.2.
