### ISSUE TITLE
Set Directory title or arrange directories doesnt work

### ISSUE THREAD

**Issue by RanVargas** [lukasgeiter/mkdocs-awesome-pages-plugin#21]
It doesn't matter if I explicitly specify in the .pages the name of the directory or the title I gave, the arrange doesn't work nor does the Set directory name work either. Example of what I am doing

in a directory named Development:
my .pages.yml file has
title: Desarrollo

which doesn't work nor produces any changes.

In another directory which has several subdirectories:

arrange:
    - Applications
    - Development
    - Standards
    - About

which doesn't work either.

**Comment by RanVargas** [comment]
I wanted to add that I am working with mkdocs 1.1 and pages-awesome 2.2.1

**Comment by lukasgeiter** [comment]
You mention your file is called `.pages.yml`. By default, the recognized filename is just `.pages` without `.yml`. If you want to use `.pages.yml`, you can change this with the [`filename` option](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#filename):

```yml
plugins:
    - awesome-pages:
        filename: .pages.yml
```

**Comment by RanVargas** [comment]
THANKS SO MUCH. I guess I missread the readme file.
