### ISSUE TITLE
Allow reverse order

### ISSUE THREAD

**Issue by MaxHalford** [lukasgeiter/mkdocs-awesome-pages-plugin#22]
Hello there,

First of all great work on this plugin, I find it really useful.

I have a usecase where I have a directory that contains release files, named `0.5.0`, `0.5.1`, etc. It makes sense to me to sort these in reverse order so that the latest release file is at the top of my toctree. There aren't too many files so I can specify the order myself, but I think it would be sweet if I could set a `reverse: True` parameter instead.

**Comment by p3kj** [comment]
I am facing the exactly same problem. This feature would be really useful in version ordering.

**Comment by lukasgeiter** [comment]
Hi everyone! I've just released v2.3.0 which adds the `order` attribute to the `.pages` file. You can set the sort order to `asc` or `desc`. To make the latest release appear at the top, you'd do this:

```markdown
order: desc
```

[See the updated README for details](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#change-sort-order).

<sup>Mentioning people who upvoted, so they get a notification as well: @pxeger, @CrossR, @ThomasG77</sup>
