### ISSUE TITLE
Hide entire menu with an `hide-menu: true` setting in .pages file

### ISSUE THREAD

**Issue by kleinen** [lukasgeiter/mkdocs-awesome-pages-plugin#23]
My group has some theme overrides setup to not render the entire nav menu of our main index page since we want the main page to be clean and the other pages are more "utility" in nature.  It would be nice if this were built-in and we didn't need the custom theme work.

It feels like this functionality best fits with this plugin, hence why this enhancement suggestion was created.

**Comment by lukasgeiter** [comment]
I'm not sure if I fully understand your request. Would this be different than setting `hide: true` in the `.pages` file of the parent folder?

**Comment by kleinen** [comment]
Well there you go being awesome.  I hadn't thought of that.  I'll give it a try.

**Comment by kleinen** [comment]
No luck.  I get an error.  I think it has to do with the menu I'm hiding being the root page menu.

```
[I 200427 18:28:34 watcher:103] Running task: builder (delay: None)
INFO    -  Running task: builder (delay: None)
INFO    -  Building documentation... 
/usr/local/lib/python3.8/site-packages/mkdocs_awesome_pages_plugin/navigation.py:48: HideInRootHasNoEffect: Using the "hide" attribute in the .pages file of the doc root has no effect
  warnings.warn(HideInRootHasNoEffect(self.options.filename))
```

**Comment by lukasgeiter** [comment]
Do you want to hide the navigation for all pages or only when the root page is selected?

**Comment by kleinen** [comment]
Only when the root page is selected.  Now that I type that, maybe this plugin is not the place for that and it would best be something added directly into mkdocs-material or its own extension/plugin.

**Comment by lukasgeiter** [comment]
I think you're probably right. This plugin currently only hooks into the `on_nav` event which is only called once for the entire build. I'm not even sure if it would be possible to change the navigation based on the selected page using a mkdocs plugin.

As far as I can tell, the right place to implement such a feature would be the theme.
