### ISSUE TITLE
support appending to generated nav?

### ISSUE THREAD

**Issue by ms-lolo** [lukasgeiter/mkdocs-awesome-pages-plugin#26]
Just wondering if it would be possible to allow me to add a set of links to the nav that are not part of the docs file structure. Right now I am linking to API docs that are generated separately from mkdocs and my `nav` config option has a few links going out to those sub-pages. When using the `awesome-pages` plugin, removing `nav` generates links to all my mkdocs pages but adding my external links makes me lose the auto-generated navigation from this plugin.

**Comment by lukasgeiter** [comment]
That is currently not possible. However, I'm planning on implementing this for the next release. I'll keep you posted.

**Comment by ms-lolo** [comment]
amazing, thank you for the great plugin!

**Comment by lukasgeiter** [comment]
Hi everyone! I've just released v2.3.0 which brings the `nav` attribute to the `.pages` file. `nav` supports adding links in the same way as it works in `mkdocs.yml`. [See the updated README for details](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#customize-navigation).

**Comment by ms-lolo** [comment]
will give this a try soon, thanks!
