### ISSUE TITLE
Minus in file title are rendered as space

### ISSUE THREAD

**Issue by JanoschDeurer** [lukasgeiter/mkdocs-awesome-pages-plugin#27]
If there is a minus in the title of a markdown file the minus is rendered as a space. I think this makes sense for underscores, because they are not part of natural language. Minus signs however are. Is there any way to configure this?

**Comment by lukasgeiter** [comment]
Do you mean the filename? If you specify the title of the page inside the markdown file, it should be used as-is:

```markdown
# Title

Content...
```

**Comment by JanoschDeurer** [comment]
Thanks for the fast response. That solves it for me :)
