### ISSUE TITLE
Hide 'home' from menu?

### ISSUE THREAD

**Issue by connerxyz** [lukasgeiter/mkdocs-awesome-pages-plugin#28]
Is there a way to hide (i.e. docs/index.md) from showing up on the tabs?

**Comment by lukasgeiter** [comment]
Currently no. I'm currently working on a new release which introduces a new `nav` option that is similar to `arrange` but allows you to hide any pages not explicitly mentioned. Would this be sufficient or do you need a way to specify what pages to hide?

**Comment by connerxyz** [comment]
I believe so. Thanks.

**Comment by lukasgeiter** [comment]
Good. Then you'll be happy to know that I've released v2.3.0 yesterday. It includes the `nav` attribute, which hides pages that are not specified unless there is a `...` entry. [See the updated README for details](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#customize-navigation).
