### ISSUE TITLE
Some issues during install

### ISSUE THREAD

**Issue by AdrienFromToulouse** [lukasgeiter/mkdocs-awesome-pages-plugin#3]
Hello,

Many thanks for maintaining this plugin.
It fills a missing part from `mkdocs` 👍 

However I am facing this issue during install:

```console
pip install mkdocs-awesome-pages-plugin
Collecting mkdocs-awesome-pages-plugin
  Could not find a version that satisfies the requirement mkdocs-awesome-pages-plugin (from versions: )
No matching distribution found for mkdocs-awesome-pages-plugin
```

Any thoughts?

Cheers!

**Comment by AdrienFromToulouse** [comment]
I do finally install using GitHub url `git+https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/#egg=mkdocs-awesome-pages-plugin` on a Docker image.

I may have had something crappy on my workstation. 
Switching to Docker + git url solved my issue.

**Comment by lukasgeiter** [comment]
Hmm but you where able to install other packages (like `mkdocs` for example) normally?

**Comment by AdrienFromToulouse** [comment]
Yes, I could install all other packages as well as `mkdocs` itself.

**Comment by beevelop** [comment]
Had the same issue on macOS, when trying to install the package with Python 2.
```
› pip --version
pip 9.0.3 from /usr/local/lib/python2.7/site-packages (python 2.7)

› pip install mkdocs-awesome-pages-plugin
Collecting mkdocs-awesome-pages-plugin
  Could not find a version that satisfies the requirement mkdocs-awesome-pages-plugin (from versions: )
No matching distribution found for mkdocs-awesome-pages-plugin

› pip3 --version
pip 9.0.3 from /usr/local/lib/python3.6/site-packages (python 3.6)

› pip3 install mkdocs-awesome-pages-plugin
# succeeds
```

You can see on PyPI, that only `py3` is available: https://pypi.org/project/mkdocs-awesome-pages-plugin/1.2.0/#files

**Comment by lukasgeiter** [comment]
Yes that's right. This package requires Python 3.5 or higher. I didn't even consider this issue because I thought pip would show a more helpful error message in that case, but apparently it does not.

I've added a note about the version requirement in the Readme, so hopefully others will find this information more easily.
