### ISSUE TITLE
Question about arrange beeing replaced by nav:

### ISSUE THREAD

**Issue by TRaSH-** [lukasgeiter/mkdocs-awesome-pages-plugin#33]
After reading the following: 
https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#arrange-pages

i tried to switch it to nav: but if i do that the build breaks with all kind of errors.

like not showing up or a 404 error.

using now the following in my docs
```yml
arrange:
    - index.md
    - dir1
    - dir2
    - dir3
    - dir4
    - dir5
    - dir6
```
in dir1 i got the following
```yml
arrange:
    - index.md
    - dir1
    - dir2
```
where index.md should be the first landing page when selected

when i change it to nav:
i get a 404 on the docs folder for the home page
and also if i go to dir1

hope i described it good enough
else i will add my actual folder names if needed

**Comment by lukasgeiter** [comment]
I don't see an immediate problem with the details you provided. The only catch when migrating from `arrange` to `nav` is that `arrange` automatically adds not listed items at the end while `nav` hides them by default.

---

I presume this is about [TRaSH-/Guides](https://github.com/TRaSH-/Guides)? If that's the case please let me know what steps to take to reproduce the issue. Or even better, push a branch that I can check out.

**Comment by TRaSH-** [comment]
This is weird,
i retried it again and now it works :S 
hmm i used to have as landing page for the sub folders a readme and changed that to a index.md now
hope it isn't a cache thing now that it looks like it works on my side.

And yes indeed it's that guide thing
i just changed it for the home screen, and sonarr/radarr

**Comment by lukasgeiter** [comment]
I'm glad it's working now. I'll close this issue, feel free to re-open if you run into the issue again.
