### ISSUE TITLE
Disable Page or Directory

### ISSUE THREAD

**Issue by erickjx** [lukasgeiter/mkdocs-awesome-pages-plugin#4]
Hi, i want disable pages o directory to scan and display, it is possible?

**Comment by lukasgeiter** [comment]
Hi! Currently that's not possible using this plugin.
What would be your use-case?

**Comment by erickjx** [comment]
Hi, i include "_snippets" directory with some useful md files with links, examples, and others things, then i used this in common with others  documents directories.

**Comment by lukasgeiter** [comment]
I see, I'll consider it when working on the next release.

**Comment by erickjx** [comment]
thanks.

**Comment by mattwilmott** [comment]
Yeah I'd 100% use this feature too. My use case is I have a folder with JS files in it that I wish not to be rendered directly

**Comment by lukasgeiter** [comment]
Sorry for the long wait. This feature is implemented and shipped with v2.1.0.  
You can now set `hide: true` in your `.pages` files to hide a directory.
