### ISSUE TITLE
Combine Custom Navigation & File Structure

### ISSUE THREAD

**Issue by greengumby** [lukasgeiter/mkdocs-awesome-pages-plugin#54]
Hi,

I can see that by using ... in the mkdocs.yml this allows the navigation tree to be seeded from the .pages files.  This is great as it will allow custom documentation to be added to the default.

It is possible to keep these completely separate.  For instance can I configure it so that all the custom documentation (including .pages) is loaded from a separate folder?

Thanks

**Comment by lukasgeiter** [comment]
I'm not sure what you mean by _custom_ and _default_ documentation. Could you make an example of what you'd like to do?

**Comment by greengumby** [comment]
Thanks @lukasgeiter,

We build a software package that has in-built help.  This is using the standard mkdocs.  However end users wish to add more documentation to what is deployed.  They do not want to change what comes out of the install but add more pages.

So an example of contents would be

- Introduction   >
- User Guide   >
- ...
- User Added documentation >

Thanks

**Comment by lukasgeiter** [comment]
Thanks for the explanation. I'm still missing the full picture of what your file structure looks like. Would the separate folder just be a subfolder of the docs directory?
