### ISSUE TITLE
Awesome pages doesn't respect specified file order over `...` pattern

### ISSUE THREAD

**Issue by Andre601** [lukasgeiter/mkdocs-awesome-pages-plugin#55]
I host a website listing sounds enum names for the SpigotMC project.

Now I want to use Awesome pages to not have to update all pages every time a new update releases, but I encounter a rather strange issue, where the order of the pages in the navigation is completely out of order.

My intended order is:
```
- Spigot 1.8.x
- Spigot 1.9.x
- Spigot 1.10.x
- Spigot 1.11.x
- Spigot 1.12.x
- Spigot 1.13.x
- Spigot 1.14.x
- Spigot 1.15.x
- Spigot 1.16.x
- Spigot 1.17.x
- Spigot 1.18.x
```
but the order as of now is
```
- Spigot 1.10.x
- Spigot 1.11.x
- Spigot 1.12.x
- Spigot 1.13.x
- Spigot 1.14.x
- Spigot 1.15.x
- Spigot 1.16.x
- Spigot 1.17.x
- Spigot 1.18.x
- Spigot 1.8.x
- Spigot 1.9.x
```
and I'm not sure if this is now caused by awesome pages, the Material theme or even MkDocs itself.

I tried to *force* awesome pages to put the 1.8 and 1.9 pages before everything else using
```yaml
nav:
- Spigot Sounds: index.md
- mc-1.8.md
- mc-1.9.md
- ...
```
but the order stays unaffected. The file names are correct.

Any idea what the issue is and how I could solve it?

**Comment by lukasgeiter** [comment]
This is a consequence of how MkDocs sorts files/pages. They are compared character by character, without any kind of special handling for (multi digit) numbers. So when the second `1` in `mc-1.10.md` is compared to the `9` in `mc-1.9.md`, `1` is smaller and therefore `mc-1.10.md` is listed before `mc-1.9.md`.

Explicitly putting `1.8` and `1.9` before `...` should've worked though. Maybe you'll want to try that again.

An alternative solution would be to add zeroes to the filenames: `mc-1.08.md`

**Comment by Andre601** [comment]
> Explicitly putting `1.8` and `1.9` before `...` should've worked though. Maybe you'll want to try that again.

Yeah... That doesn't work for some reason

**Comment by lukasgeiter** [comment]
But the `nav` feature works for other pages?

**Comment by Andre601** [comment]
> But the `nav` feature works for other pages?

Idk.
I don't use that specific nav setups on other pages.

**Comment by lukasgeiter** [comment]
Okay, I've looked at your repo. The file needs to be called `.pages` (without an extension).

You're not the first person to run into this, so I might change it so it also works with an extension...

**Comment by Andre601** [comment]
Strangely enough did it not work when I had only `.pages`

It's rather strange. And personally should it just use extensions, because of other things like syntax highlighting in text editors...

**Comment by lukasgeiter** [comment]
In hindsight I agree, having a file extension makes more sense... I'll see that I can enable support for `.pages.yml` out of the box.

In the meantime, you can customize the [`filename` using a plugin option](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#filename).

**Comment by Andre601** [comment]
I for now changed the filenames and the nav is working as it should, thanks
