### ISSUE TITLE
Menu not rendered when using macros

### ISSUE THREAD

**Issue by BoxedBrain** [lukasgeiter/mkdocs-awesome-pages-plugin#66]
Hi,

I am using [macros](https://mkdocs-macros-plugin.readthedocs.io/) inside some H1 tags.
e.g. `# Welcome to {{about.product}}`

The page title works as expected, but inside the menu it's displayed raw.
Is it somehow possible to solve that without specifying the menu entry manually inside the `.pages` file or H1 tag?

Thanks!

**Comment by lukasgeiter** [comment]
Does it work correctly if you're not using awesome-pages?

**Comment by BoxedBrain** [comment]
Good point, I just tested and indeed it does not work without awesome-pages.
So I guess I need to open the issue within [mkdocs_macros_plugin](/fralau/mkdocs_macros_plugin).

Thanks!
