### ISSUE TITLE
Indented `...` breaks `.pages` in subdirectories

### ISSUE THREAD

**Issue by HactarCE** [lukasgeiter/mkdocs-awesome-pages-plugin#77]
[`docs/.pages`](https://github.com/Hypercubers/hypercubing.xyz/blob/1e8fecf1fe120d5e67fe21142d5c0ce143c67852/docs/.pages) has these contents:
```
nav:
  - Wiki:
    - index.md
    - ...
  - faq.md
  - leaderboards
```

and [`docs/.pages/puzzles/physical-puzzles/phys-2x2x2x2/.pages`](https://github.com/Hypercubers/hypercubing.xyz/blob/1e8fecf1fe120d5e67fe21142d5c0ce143c67852/docs/puzzles/physical-puzzles/phys-2x2x2x2/.pages) contains this:
```
title: Melinda's 2x2x2x2
```

but as long as `- ...` is indented under `Wiki:`, the second `.pages` file is completely ignored. If I unindent it to the same level as `faq.md`, then it works as intended.

**Comment by lukasgeiter** [comment]
Thank you for reporting the bug. The fix is included in version 2.9.2.
