### ISSUE TITLE
folder level .pages nav not working when top level .pages nav has sub-sections?

### ISSUE THREAD

**Issue by paulinestacey** [lukasgeiter/mkdocs-awesome-pages-plugin#81]
My docs project has a top level .page nav which I've edited to show some sub-sections (at the folder level). The top nav now renders exactly as we want it, but the .pages nav files within the folders are being ignored so the docs files are rendering in default order with default titles. If I reinstate the original top level .page nav without sub-sections, all the .pages navs in the project render correctly.
Any one else had this? got suggestions to fix?
Many thanks :)

(PS. running Mkdocs 1.5.2, Material 9.1.21, awesome-pages-plugin 2.8.0)

**Comment by lukasgeiter** [comment]
First I would ask you to update the plugin to the latest version. If the issue persists, please provide more details (file structure and contents of relevant files) or a full example project.

**Comment by paulinestacey** [comment]
That's perfect, thanks. Upgrade to 2.9.2 fixed the issue. :)
