### ISSUE TITLE
Can nav be sorted by date?

### ISSUE THREAD

**Issue by Andre601** [lukasgeiter/mkdocs-awesome-pages-plugin#85]
I would like to sort pages based on date, by which I refer to page meta.

Does the plugin support this?

**Comment by lukasgeiter** [comment]
Currently there's no support for sorting by date. Just to be clear, you mean a date in the frontmatter like so?

```
---
title: My Document
date: 2018-07-10
---
```

**Comment by Andre601** [comment]
Yes.
Tho, now that I look a bit closer do I feel like this option wouldn't help my case anyways.

Currently try to sort a `nav` object's `pages` list by date (or some other attribute). And while awesome-pages does change the order in the displayed nav, does the `pages` list seem unaffected by this change and still return entries in the original order (based on filename).

You can find my current struggles on this [here](https://github.com/mkdocs/mkdocs/discussions/3376) in case you have any input...

**Comment by lukasgeiter** [comment]
Yeah, this plugin is for customizing the navigation. To sort pages for your timeline, you're better off doing that without this plugin. Good luck with your project!
