### ISSUE TITLE
Possible to build full nav in directory?

### ISSUE THREAD

**Issue by joawan** [lukasgeiter/mkdocs-awesome-pages-plugin#91]
Given a structure like
```
docs/
  index.md
  folder1/
    file.md
    file2.md
```

and a .pages file like
```
nav:
  - index.md
  - title
    - folder1/file.md
    - folder1/file2.md
```

This renders an `NavEntryNotFound` error.

If setting a title like
```
    - File 2: 'folder1/file2.md'
```
there is no error thrown, but the link in the nav becomes `folder1/file2.md` and thereby a 404.

Is there a way to build a nav structure with subfolders etc?

**Comment by kamilkrzyskow** [comment]
Instead of `title` you should write `folder1` without any structure beneath it.
Then if you want to set a title or change the structure of that folder's nav you create a .pages file inside that folder.

**Comment by kamilkrzyskow** [comment]
Here is an example:
https://github.com/Gothic-Modding-Community/gmc/blob/dev/docs/.pages
https://github.com/Gothic-Modding-Community/gmc/blob/dev/docs/zengin/.pages

**Comment by kamilkrzyskow** [comment]
Yes
