### ISSUE TITLE
An absolute path to '/...' is included in the 'nav' configuration, which presumably points to an external

### ISSUE THREAD

**Issue by viceice** [lukasgeiter/mkdocs-awesome-pages-plugin#92]
We're getting this message when using this plugin:
```
An absolute path to '/...' is included in the 'nav' configuration, which presumably points to an external
```

We're not sure how to suppress that, because it will cause an error if we enable strict mkdocs checks.

- https://github.com/renovatebot/renovatebot.github.io/pull/305
- https://github.com/squidfunk/mkdocs-material/discussions/6318

**Comment by lukasgeiter** [comment]
Do you have an example that I could use to reproduce the issue?

**Comment by viceice** [comment]
only our repo / PR linked above, sorry.

**Comment by viceice** [comment]
will try to create a reproduction

**Comment by kamilkrzyskow** [comment]
@lukasgeiter 
This should do as a minimal reproduction, simple `mkdocs new` with all of the new validation features enabled.
[mkdocs-awesome-issue.zip](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/files/13501816/mkdocs-awesome-issue.zip)
I believe that _validation_ of the `nav` comes before the plugin processes the `...` in the `mkdocs.yml` `nav`

@viceice 
As for your case, have you tried removing the nav from the `mkdocs.yml`, do you really need that to insert the `.pages` navigation properly on the root level?

**Comment by viceice** [comment]
@kamilkrzyskow Thanks, removing `nav` from `mkdoc.yml` solved the error.
