### ISSUE TITLE
Order does not take effect for subdirectory files

### ISSUE THREAD

**Issue by shenweiyan** [lukasgeiter/mkdocs-awesome-pages-plugin#95]
Hi, I encountered some issues while using awesome-pages and would like to seek advice on how to resolve them.

My docs directory structure is as follows:
```
docs/
├── README.md
├── dirNamedA
│   ├── .pages
│   ├── dirA-page01.md
│   ├── dirA-page02.md
│   └── subDirNamedA1
│   │   ├── subDirA1-page01.md
│   │   └── subDirA1-page02.md
│   └── subDirNamedA2
│       ├── subDirA2-page01.md
│       └── subDirA2-page02.md
├── dirNamedB
│   ├── dirB-page01.md
│   ├── dirB-page02.md
│   └── subDirNamedB1
│       ├── subDirB1-page01.md
│       └── subDirB1-page02.md
└── emptyDir
```
My `docs/dirNamedA/.pages` is as follows, but `desc` seems not work for the posts in `subDirNamedA1` and `subDirNamedA2` posts.
```
order: desc
order_by: filename
```

**Comment by lukasgeiter** [comment]
The `order` setting doesn't apply to subdirectories. You can [override the default in `mkdocs.yml` though](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin?tab=readme-ov-file#options).

**Comment by shenweiyan** [comment]
> The `order` setting doesn't apply to subdirectories. You can [override the default in `mkdocs.yml` though](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin?tab=readme-ov-file#options).

Thank you very much.
